const ACTION_ID = "NAVIGATION ACTIONS";

export const STACK_DEEP_FOCUSED = `[${ACTION_ID}] STACK DEEP FOCUSED`;
export const STACK_MAIN_FOCUSED = `[${ACTION_ID}] STACK MAIN FOCUSED`;
export const CHANGE_INITIAL_ROUTE = `[${ACTION_ID}] CHANGE INITIAL ROUTE`;

